### ISSUE TITLE
error when training chengyubert-twostage

### ISSUE THREAD

**Issue by chenzhengdeeplearning** [VisualJoyce/ChengyuBERT#4]
`
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_official.py", line 468, in <module>
[1,0]<stderr>:    main(args)
[1,0]<stderr>:  File "train_official.py", line 317, in main
[1,0]<stderr>:    best_ckpt = train(model, dataloaders, opts)
[1,0]<stderr>:  File "train_official.py", line 145, in train
[1,0]<stderr>:    opts, global_step)
[1,0]<stderr>:  File "train_official.py", line 235, in evaluation
[1,0]<stderr>:    log.update(validate(opts, model, loader, split, global_step))
[1,0]<stderr>:  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "train_official.py", line 176, in validate
[1,0]<stderr>:    logits, over_logits, cond_logits = model(**batch, targets=None, compute_loss=False)
[1,0]<stderr>:ValueError: not enough values to unpack (expected 3, got 2)

`

**Comment by VisualJoyce** [comment]
`chengyubert-twostage` is not released yet because the paper is still under review.

**Comment by chenzhengdeeplearning** [comment]
oh...Thanks a lot
